in:
  type: http_json
  scheme: http
  host: localhost
  port: 8080
  path: /example
  method: GET
  transformer: '.response_body.integerValues'
  success_condition_jq: '.status_code_class == 200'
out:
  type: stdout
